version: '3.7'
services:
  opensearch:
    container_name: opensearch
    image: hasecuritysolutions/opensearch:2.7.0
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g
    healthcheck:
        test: [ "CMD", "nc", "-z", "-v", "127.0.0.1", "9300" ]
        interval: 30s
        timeout: 10s
        retries: 10
    networks:
      - reflex
    restart: always
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
      - INSTALLDIR/internal_users.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/internal_users.yml
      - INSTALLDIR/roles.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/roles.yml
      - INSTALLDIR/roles_mapping.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/roles_mapping.yml
      - INSTALLDIR/action_groups.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/action_groups.yml
      - INSTALLDIR/nodes_dn.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/nodes_dn.yml
      - INSTALLDIR/whitelist.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/whitelist.yml
      - INSTALLDIR/config.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/config.yml
  memcached:
    container_name: memcached
    image: hasecuritysolutions/memcached:latest
    command: ["-m", "1024"]
    networks:
      - reflex
    restart: always
    healthcheck:
        test: [ "CMD-SHELL", "echo 'stats' | nc localhost 11211" ]
        interval: 30s
        timeout: 10s
        retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  opensearch-data1:

networks:
  reflex:
