version: '3.7'
services:
  opensearch:
    container_name: opensearch
    image: hasecuritysolutions/opensearch:${OPENSEARCH_STACK_VERSION}
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms${OPENSEARCH_JAVA_HEAP}g -Xmx${OPENSEARCH_JAVA_HEAP}g
    healthcheck:
        test: [ "CMD", "nc", "-z", "-v", "127.0.0.1", "9300" ]
        interval: 30s
        timeout: 10s
        retries: 10
    networks:
      - reflex
    restart: always
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
      - INSTALLDIR/internal_users.yml:/usr/share/opensearch/config/opensearch-security/internal_users.yml
      - INSTALLDIR/roles.yml:/usr/share/opensearch/config/opensearch-security/roles.yml
      - INSTALLDIR/roles_mapping.yml:/usr/share/opensearch/config/opensearch-security/roles_mapping.yml
      - INSTALLDIR/action_groups.yml:/usr/share/opensearch/config/opensearch-security/action_groups.yml
      - INSTALLDIR/nodes_dn.yml:/usr/share/opensearch/config/opensearch-security/nodes_dn.yml
      - INSTALLDIR/whitelist.yml:/usr/share/opensearch/config/opensearch-security/whitelist.yml
      - INSTALLDIR/config.yml:/usr/share/opensearch/config/opensearch-security/config.yml
      - INSTALLDIR/tenants.yml:/usr/share/opensearch/config/opensearch-security/tenants.yml
  opensearch-dashboards:
    container_name: opensearch-dashboards
    image: opensearchproject/opensearch-dashboards:${OPENSEARCH_STACK_VERSION}
    depends_on:
      opensearch:
        condition: service_healthy
    ports:
      - 5601:5601
    volumes:
      - ./custom-opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
      - ./opensearch_dashboards.key:/usr/share/opensearch-dashboards/config/opensearch-dashboards.key
      - ./opensearch_dashboards.crt:/usr/share/opensearch-dashboards/config/opensearch-dashboards.crt
    networks:
      - reflex
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  memcached:
    container_name: memcached
    image: hasecuritysolutions/memcached:6.21.2022
    command: ["-m", "1024"]
    networks:
      - reflex
    restart: always
    healthcheck:
        test: [ "CMD-SHELL", "echo 'stats' | nc localhost 11211" ]
        interval: 30s
        timeout: 10s
        retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  reflex-api:
    container_name: reflex-api
    environment:
      #- GUNICORN_WORKER_CLASS=gthread
      - REFLEX_ES_URL=opensearch:9200
      - REFLEX_DISABLE_SLAMONITOR=true
      - REFLEX_ES_USERNAME=admin
      - REFLEX_ES_PASSWORD=STORAGEADMINPASSWORD
      #- REFLEX_ES_CA=/ca.crt
      #- REFLEX_ES_CERT_VERIFY=none
      - REFLEX_ES_AUTH_SCHEMA=http
      - REFLEX_ES_DISTRO=opensearch
      - REFLEX_LOG_LEVEL=INFO
      - REFLEX_ES_TIMEOUT=120
      - REFLEX_EVENT_PROCESSOR_ES_BULK_SIZE=250
      - REFLEX_ELASTIC_APM_ENABLED=false
      - REFLEX_THREAT_POLLER_MEMCACHED_ENABLED=true
      - REFLEX_THREAT_POLLER_MEMCACHED_HOST=memcached
      - REFLEX_THREAT_POLLER_MEMCACHED_PORT=11211
      - REFLEX_THREAT_POLLER_MEMCACHED_TTL=60
    image: zeroonesec/reflex-api:version-2023.05.00-sec555
    depends_on:
      opensearch:
        condition: service_healthy
    healthcheck:
        test: [ "CMD", "curl", "--silent", "--fail", "http://localhost/api/v2.0/" ]
        interval: 10s
        timeout: 10s
        retries: 10
        start_period: 600s
    volumes:
      - ./application.conf:/instance/application.conf
    networks:
      - reflex
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  reflex-ui:
    container_name: reflex-ui
    image: zeroonesec/reflex-ui:version-2023.05.00-sec555
    depends_on:
      reflex-api:
        condition: service_healthy
    healthcheck:
        test: [ "CMD", "curl", "--silent", "--fail", "--insecure", "https://localhost" ]
        interval: 10s
        timeout: 10s
        retries: 10
        start_period: 600s
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 443:443
    networks:
      - reflex
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  opensearch-data1:

networks:
  reflex:
